name: Node.js CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
permissions:
  contents: read

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: No operation
        run: echo "..."
